theme: jekyll-theme-leap-day
show_downloads: true
github:
  zip_url: https://github.com/myosminozhka-ru/gulp-builder/archive/refs/tags/tag.zip
  tar_url: https://github.com/myosminozhka-ru/gulp-builder/archive/refs/tags/tag.tar.gz
